### PR TITLE
Turkish translate

### PR DESCRIPTION
**Pull request by c0b41**
not ready don't merge.
thnx. :+1:

### CODE REVIEW

**Comment by krambertech** [comment]
Thank you! That's awesome!

**Comment by c0b41** [comment]
@krambertech Thanks, translation is over :)

**Comment by koorchik** [comment]
All checks have failed

**Comment by krambertech** [comment]
That's  something with Travis 

```
> itsquiz-wall@0.0.1 test /home/travis/build/WebbyLab/itsquiz-wall
> npm run lint
> itsquiz-wall@0.0.1 lint /home/travis/build/WebbyLab/itsquiz-wall
> eslint shared client server
Error: Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at monkeypatch (/home/travis/build/WebbyLab/itsquiz-wall/node_modules/babel-eslint/index.js:59:32)
    at Object.exports.parse (/home/travis/build/WebbyLab/itsquiz-wall/node_modules/babel-eslint/index.js:385:5)
    at parse (/home/travis/build/WebbyLab/itsquiz-wall/node_modules/eslint/lib/eslint.js:578:27)
    at EventEmitter.module.exports.api.verify (/home/travis/build/WebbyLab/itsquiz-wall/node_modules/eslint/lib/eslint.js:716:19)
    at processText (/home/travis/build/WebbyLab/itsquiz-wall/node_modules/eslint/lib/cli-engine.js:187:27)
    at processFile (/home/travis/build/WebbyLab/itsquiz-wall/node_modules/eslint/lib/cli-engine.js:227:18)
    at executeOnFile (/home/travis/build/WebbyLab/itsquiz-wall/node_modules/eslint/lib/cli-engine.js:603:23)
```

**Comment by c0b41** [comment]
@koorchik @krambertech  see https://github.com/eslint/eslint/issues/5476

**Pull request merged**
